services:
  postgres:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_USER: mypharma
      POSTGRES_PASSWORD: mypharma
      POSTGRES_DB: mypharma
      TZ: Europe/Athens
      POSTGRES_INITDB_ARGS: "--locale=el_GR.UTF-8"
    command: ["postgres", "-c", "timezone=Europe/Athens"]
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
