import { CityConfig } from '../types';

// Αττικής (495 cities) - extracted from xo.gr
export const ATTIKIS_CITIES: CityConfig[] = [
  { name: 'Αγία Αναστασία (Περιστέρι Αττικής)', slug: 'agia-anastasia-peristeri-attikis', prefecture: 'Αττικής' },
  { name: 'Αγία Βαρβάρα', slug: 'agia-varvara-attikis', prefecture: 'Αττικής' },
  { name: 'Αγία Βαρβάρα (Αργυρούπολη Αττικής)', slug: 'agia-varvara-argyroupoli-attikis', prefecture: 'Αττικής' },
  { name: 'Αγία Βαρβάρα (Δάφνη Αττικής)', slug: 'agia-varvara-dafni-attikis', prefecture: 'Αττικής' },
  { name: 'Αγία Βαρβάρα (Ίλιον Αττικής)', slug: 'agia-varvara-ilion-attikis', prefecture: 'Αττικής' },
  { name: 'Αγία Βαρβάρα (Λυκόβρυση - Μεταμόρφωση)', slug: 'agia-varvara-lykovrysi-metamorfosi', prefecture: 'Αττικής' },
  { name: 'Αγία Βαρβάρα (Παλαιό Φάληρο Αττικής)', slug: 'agia-varvara-palaio-faliro-attikis', prefecture: 'Αττικής' },
  { name: 'Αγία Γλυκερία (Γαλάτσι - Αθήνα)', slug: 'agia-glykeria-galatsi-athina', prefecture: 'Αττικής' },
  { name: 'Αγία Ειρήνη (Γαλάτσι Αττικής)', slug: 'agia-eirini-galatsi-attikis', prefecture: 'Αττικής' },
  { name: 'Αγία Ειρήνη (Λυκόβρυση Αττικής)', slug: 'agia-eirini-lykovrysi-attikis', prefecture: 'Αττικής' },
  { name: 'Αγία Ελεούσα (Αγία Βαρβάρα Αττικής)', slug: 'agia-eleousa-agia-varvara-attikis', prefecture: 'Αττικής' },
  { name: 'Αγία Ελεούσα (Καλλιθέα Αττικής)', slug: 'agia-eleousa-kallithea-attikis', prefecture: 'Αττικής' },
  { name: 'Αγία Ευφημία (Νέα Χαλκηδόνα Αττικής)', slug: 'agia-effimia-nea-chalkidona-attikis', prefecture: 'Αττικής' },
  { name: 'Αγία Ζώνη (Αθήνα)', slug: 'agia-zoni-athina', prefecture: 'Αττικής' },
  { name: 'Αγία Κυριακή (Παλαιό Φάληρο Αττικής)', slug: 'agia-kyriaki-palaio-faliro-attikis', prefecture: 'Αττικής' },
  { name: 'Αγία Μαρίνα (Ζωγράφος Αττικής)', slug: 'agia-marina-zografos-attikis', prefecture: 'Αττικής' },
  { name: 'Αγία Μαρίνα (Μελίσσια Αττικής)', slug: 'agia-marina-melissia-attikis', prefecture: 'Αττικής' },
  { name: 'Αγία Μαρίνα (Νέα Φιλαδέλφεια Αττικής)', slug: 'agia-marina-nea-filadelfeia-attikis', prefecture: 'Αττικής' },
  { name: 'Αγία Μαρίνα Κρωπίας Αττικής', slug: 'agia-marina-kropias-attikis', prefecture: 'Αττικής' },
  { name: 'Αγία Παρασκευή', slug: 'agia-paraskevi-attikis', prefecture: 'Αττικής' },
  { name: 'Αγία Παρασκευή (Ελληνικό Αττικής)', slug: 'agia-paraskevi-elliniko-attikis', prefecture: 'Αττικής' },
  { name: 'Αγία Παρασκευή (Κηφισιά Αττικής)', slug: 'agia-paraskevi-kifisia-attikis', prefecture: 'Αττικής' },
  { name: 'Αγία Παρασκευή (Νέα Σμύρνη Αττικής)', slug: 'agia-paraskevi-nea-smyrni-attikis', prefecture: 'Αττικής' },
  { name: 'Αγία Σοφία (Νέο Ψυχικό Αττικής)', slug: 'agia-sofia-neo-psychiko-attikis', prefecture: 'Αττικής' },
  { name: 'Αγία Σοφία (Ταύρος Αττικής)', slug: 'agia-sofia-tayros-attikis', prefecture: 'Αττικής' },
  { name: 'Αγία Τριάδα - Πεύκα Βέρδη (Πετρούπολη Αττικής)', slug: 'agia-triada-peyka-verdi-petroupoli-attikis', prefecture: 'Αττικής' },
  { name: 'Αγία Τριάδα (Αιγάλεω Αττικής)', slug: 'agia-triada-aigaleo-attikis', prefecture: 'Αττικής' },
  { name: 'Αγία Τριάδα (Αργυρούπολη Αττικής)', slug: 'agia-triada-argyroupoli-attikis', prefecture: 'Αττικής' },
  { name: 'Αγία Τριάδα (Γλυφάδα Αττικής)', slug: 'agia-triada-glyfada-attikis', prefecture: 'Αττικής' },
  { name: 'Αγία Τριάδα (Ηράκλειο Αττικής)', slug: 'agia-triada-irakleio-attikis', prefecture: 'Αττικής' },
  { name: 'Αγία Τριάδα (Καματερό Αττικής)', slug: 'agia-triada-kamatero-attikis', prefecture: 'Αττικής' },
  { name: 'Αγία Τριάδα (Νέα Φιλαδέλφεια Αττικής)', slug: 'agia-triada-nea-filadelfeia-attikis', prefecture: 'Αττικής' },
  { name: 'Αγία Τριάδα (Χολαργός Αττικής)', slug: 'agia-triada-cholargos-attikis', prefecture: 'Αττικής' },
  { name: 'Αγία Φωτεινή (Νέα Σμύρνη Αττικής)', slug: 'agia-foteini-nea-smyrni-attikis', prefecture: 'Αττικής' },
  { name: 'Άγιοι Ακίνδυνοι (Άγιοι Ανάργυροι Αττικής)', slug: 'agioi-akindynoi-agioi-anargyroi-attikis', prefecture: 'Αττικής' },
  { name: 'Άγιοι Ανάργυροι', slug: 'agioi-anargyroi-attikis', prefecture: 'Αττικής' },
  { name: 'Άγιοι Ανάργυροι (Αγία Βαρβάρα Αττικής)', slug: 'agioi-anargyroi-agia-varvara-attikis', prefecture: 'Αττικής' },
  { name: 'Άγιοι Ανάργυροι (Μαρούσι Αττικής)', slug: 'agioi-anargyroi-marousi-attikis', prefecture: 'Αττικής' },
  { name: 'Άγιοι Ανάργυροι (Νέα Ιωνία Αττικής)', slug: 'agioi-anargyroi-nea-ionia-attikis', prefecture: 'Αττικής' },
  { name: 'Άγιοι Θεόδωροι Γαργηττού (Γέρακας Αττικής)', slug: 'agioi-theodoroi-gargittou-gerakas-attikis', prefecture: 'Αττικής' },
  { name: 'Άγιοι Πάντες (Αγία Βαρβάρα - Κορυδαλλός)', slug: 'agioi-pantes-agia-varvara-korydallos', prefecture: 'Αττικής' },
  { name: 'Άγιοι Ταξιάρχες (Ηράκλειο Αττικής)', slug: 'agioi-taxiarches-irakleio-attikis', prefecture: 'Αττικής' },
  { name: 'Άγιοι Ταξιάρχες (Περιστέρι Αττικής)', slug: 'agioi-taxiarches-peristeri-attikis', prefecture: 'Αττικής' },
  { name: 'Άγιος Ανδρέας (Νέα Μάκρη Αττικής)', slug: 'agios-andreas-nea-makri-attikis', prefecture: 'Αττικής' },
  { name: 'Άγιος Ανδρέας (Παιανία Αττικής)', slug: 'agios-andreas-paiania-attikis', prefecture: 'Αττικής' },
  { name: 'Άγιος Ανδρέας (Χαϊδάρι Αττικής)', slug: 'agios-andreas-chaidari-attikis', prefecture: 'Αττικής' },
  { name: 'Άγιος Αντώνιος (Περιστέρι Αττικής)', slug: 'agios-antonios-peristeri-attikis', prefecture: 'Αττικής' },
  { name: 'Άγιος Αρτέμιος - Γούβα (Αθήνα)', slug: 'agios-artemios-gouva-athina', prefecture: 'Αττικής' },
  { name: 'Άγιος Βασίλειος - Ελιά (Άγιος Δημήτριος Αττικής)', slug: 'agios-vasileios-elia-agios-dimitrios-attikis', prefecture: 'Αττικής' },
  { name: 'Άγιος Βασίλειος (Περιστέρι Αττικής)', slug: 'agios-vasileios-peristeri-attikis', prefecture: 'Αττικής' },
  { name: 'Άγιος Βλάσιος (Αχαρνές Αττικής)', slug: 'agios-vlasios-acharnes-attikis', prefecture: 'Αττικής' },
  { name: 'Άγιος Γεώργιος (Βουλιαγμένη Αττικής)', slug: 'agios-georgios-vouliagmeni-attikis', prefecture: 'Αττικής' },
  { name: 'Άγιος Γεώργιος (Ζωγράφος Αττικής)', slug: 'agios-georgios-zografos-attikis', prefecture: 'Αττικής' },
  { name: 'Άγιος Γεώργιος (Ηράκλειο Αττικής)', slug: 'agios-georgios-irakleio-attikis', prefecture: 'Αττικής' },
  { name: 'Άγιος Γεώργιος (Καματερό Αττικής)', slug: 'agios-georgios-kamatero-attikis', prefecture: 'Αττικής' },
  { name: 'Άγιος Γεώργιος (Νέο Ψυχικό Αττικής)', slug: 'agios-georgios-neo-psychiko-attikis', prefecture: 'Αττικής' },
  { name: 'Άγιος Γεώργιος (Παπάγος Αττικής)', slug: 'agios-georgios-papagos-attikis', prefecture: 'Αττικής' },
  { name: 'Άγιος Γεώργιος (Πέραμα Αττικής)', slug: 'agios-georgios-perama-attikis', prefecture: 'Αττικής' },
  { name: 'Άγιος Γεώργιος (Περιστέρι Αττικής)', slug: 'agios-georgios-peristeri-attikis', prefecture: 'Αττικής' },
  { name: 'Άγιος Δημήτριος (Κηφισιά Αττικής)', slug: 'agios-dimitrios-kifisia-attikis', prefecture: 'Αττικής' },
  { name: 'Άγιος Δημήτριος (Πετρούπολη Αττικής)', slug: 'agios-dimitrios-petroupoli-attikis', prefecture: 'Αττικής' },
  { name: 'Άγιος Δημήτριος Αττικής', slug: 'agios-dimitrios-attikis', prefecture: 'Αττικής' },
  { name: 'Άγιος Διονύσιος - Ραδιοφωνία (Ίλιον Αττικής)', slug: 'agios-dionysios-radiofonia-ilion-attikis', prefecture: 'Αττικής' },
  { name: 'Άγιος Ελευθέριος (Αθήνα)', slug: 'agios-eleftherios-athina', prefecture: 'Αττικής' },
  { name: 'Άγιος Ελευθέριος (Περιστέρι Αττικής)', slug: 'agios-eleftherios-peristeri-attikis', prefecture: 'Αττικής' },
  { name: 'Άγιος Θεράπων (Ζωγράφος Αττικής)', slug: 'agios-therapon-zografos-attikis', prefecture: 'Αττικής' },
  { name: 'Άγιος Θωμάς (Μαρούσι Αττικής)', slug: 'agios-thomas-marousi-attikis', prefecture: 'Αττικής' },
  { name: 'Άγιος Ιερόθεος (Περιστέρι Αττικής)', slug: 'agios-ierotheos-peristeri-attikis', prefecture: 'Αττικής' },
  { name: 'Άγιος Ιωάννης (Αγία Παρασκευή Αττικής)', slug: 'agios-ioannis-agia-paraskevi-attikis', prefecture: 'Αττικής' },
  { name: 'Άγιος Ιωάννης (Αθήνα - Δάφνη)', slug: 'agios-ioannis-athina-dafni', prefecture: 'Αττικής' },
  { name: 'Άγιος Ιωάννης (Παπάγος Αττικής)', slug: 'agios-ioannis-papagos-attikis', prefecture: 'Αττικής' },
  { name: 'Άγιος Κοσμάς (Νέα Φιλαδέλφεια Αττικής)', slug: 'agios-kosmas-nea-filadelfeia-attikis', prefecture: 'Αττικής' },
  { name: 'Άγιος Κωνσταντίνος (Άγιος Δημήτριος - Άλιμος)', slug: 'agios-konstantinos-agios-dimitrios-alimos', prefecture: 'Αττικής' },
  { name: 'Άγιος Κωνσταντίνος (Αιγάλεω Αττικής)', slug: 'agios-konstantinos-aigaleo-attikis', prefecture: 'Αττικής' },
  { name: 'Άγιος Κωνσταντίνος (Γλυφάδα Αττικής)', slug: 'agios-konstantinos-glyfada-attikis', prefecture: 'Αττικής' },
  { name: 'Άγιος Κωνσταντίνος (Ηλιούπολη Αττικής)', slug: 'agios-konstantinos-ilioupoli-attikis', prefecture: 'Αττικής' },
  { name: 'Άγιος Λουκάς (Αθήνα)', slug: 'agios-loukas-athina', prefecture: 'Αττικής' },
  { name: 'Άγιος Νικόλαος - Δαβάκη (Καλλιθέα Αττικής)', slug: 'agios-nikolaos-davaki-kallithea-attikis', prefecture: 'Αττικής' },
  { name: 'Άγιος Νικόλαος (Αθήνα)', slug: 'agios-nikolaos-athina', prefecture: 'Αττικής' },
  { name: 'Άγιος Νικόλαος (Γλυφάδα Αττικής)', slug: 'agios-nikolaos-glyfada-attikis', prefecture: 'Αττικής' },
  { name: 'Άγιος Νικόλαος (Ηλιούπολη Αττικής)', slug: 'agios-nikolaos-ilioupoli-attikis', prefecture: 'Αττικής' },
  { name: 'Άγιος Νικόλαος (Ίλιον - Καματερό)', slug: 'agios-nikolaos-ilion-kamatero', prefecture: 'Αττικής' },
  { name: 'Άγιος Νικόλαος (Καισαριανή Αττικής)', slug: 'agios-nikolaos-kaisariani-attikis', prefecture: 'Αττικής' },
  { name: 'Άγιος Νικόλαος (Λεοντάρι Αττικής)', slug: 'agios-nikolaos-leontari-attikis', prefecture: 'Αττικής' },
  { name: 'Άγιος Νικόλαος (Μαρούσι Αττικής)', slug: 'agios-nikolaos-marousi-attikis', prefecture: 'Αττικής' },
  { name: 'Άγιος Παντελεήμονας (Αθήνα)', slug: 'agios-panteleimonas-athina', prefecture: 'Αττικής' },
  { name: 'Άγιος Παντελεήμονας (Άλιμος Αττικής)', slug: 'agios-panteleimonas-alimos-attikis', prefecture: 'Αττικής' },
  { name: 'Άγιος Παντελεήμονας (Πεύκη Αττικής)', slug: 'agios-panteleimonas-peyki-attikis', prefecture: 'Αττικής' },
  { name: 'Άγιος Παύλος (Περιστέρι Αττικής)', slug: 'agios-paylos-peristeri-attikis', prefecture: 'Αττικής' },
  { name: 'Άγιος Πέτρος (Αχαρνές Αττικής)', slug: 'agios-petros-acharnes-attikis', prefecture: 'Αττικής' },
  { name: 'Άγιος Πέτρος (Παλαιό Φάληρο Αττικής)', slug: 'agios-petros-palaio-faliro-attikis', prefecture: 'Αττικής' },
  { name: 'Άγιος Ραφαήλ (Περιστέρι Αττικής)', slug: 'agios-rafail-peristeri-attikis', prefecture: 'Αττικής' },
  { name: 'Άγιος Σπυρίδωνας (Αιγάλεω Αττικής)', slug: 'agios-spyridonas-aigaleo-attikis', prefecture: 'Αττικής' },
  { name: 'Άγιος Σπυρίδωνας (Καματερό Αττικής)', slug: 'agios-spyridonas-kamatero-attikis', prefecture: 'Αττικής' },
  { name: 'Άγιος Στέφανος', slug: 'agios-stefanos-attikis', prefecture: 'Αττικής' },
  { name: 'Άγιος Στέφανος (Νέα Ιωνία Αττικής)', slug: 'agios-stefanos-nea-ionia-attikis', prefecture: 'Αττικής' },
  { name: 'Άγιος Σώστης (Αθήνα)', slug: 'agios-sostis-athina', prefecture: 'Αττικής' },
  { name: 'Άγιος Τρύφωνας (Καματερό Αττικής)', slug: 'agios-tryfonas-kamatero-attikis', prefecture: 'Αττικής' },
  { name: 'Αγριληός - Μοναστήριο (Άγιος Δημήτριος Αττικής)', slug: 'agrilios-monastirio-agios-dimitrios-attikis', prefecture: 'Αττικής' },
  { name: 'Αθήνα - Πειραιάς', slug: 'athina-peiraias', prefecture: 'Αττικής' },
  { name: 'Αθήνα (Κέντρο - Δήμος)', slug: 'athina', prefecture: 'Αττικής' },
  { name: 'Αιάντειο Σαλαμίνας', slug: 'aianteio-salaminas', prefecture: 'Αττικής' },
  { name: 'Αιγάλεω', slug: 'aigaleo-attikis', prefecture: 'Αττικής' },
  { name: 'Αιξωνή (Γλυφάδα Αττικής)', slug: 'aixoni-glyfada-attikis', prefecture: 'Αττικής' },
  { name: 'Ακαδημία (Αθήνα)', slug: 'akadimia-athina', prefecture: 'Αττικής' },
  { name: 'Ακτή Αλίμου - Λουτρά (Άλιμος Αττικής)', slug: 'akti-alimou-loutra-alimos-attikis', prefecture: 'Αττικής' },
  { name: 'Ακτημόνων (Γαλάτσι Αττικής)', slug: 'aktimonon-galatsi-attikis', prefecture: 'Αττικής' },
  { name: 'Άλσος (Νέα Σμύρνη Αττικής)', slug: 'alsos-nea-smyrni-attikis', prefecture: 'Αττικής' },
  { name: 'Αλσούπολη (Νέα Ιωνία Αττικής)', slug: 'alsoupoli-nea-ionia-attikis', prefecture: 'Αττικής' },
  { name: 'Αλυκός (Αγία Μαρίνα - Άγιος Δημήτριος Κρωπίας)', slug: 'alykos-agia-marina-agios-dimitrios-kropias', prefecture: 'Αττικής' },
  { name: 'Αλώνια - Πλακάκια (Αχαρνές Αττικής)', slug: 'alonia-plakakia-acharnes-attikis', prefecture: 'Αττικής' },
  { name: 'Αλώνια (Βάρη Αττικής)', slug: 'alonia-vari-attikis', prefecture: 'Αττικής' },
  { name: 'Αμπέλι Κλεινός - Πατητήρι (Αχαρνές Αττικής)', slug: 'ampeli-kleinos-patitiri-acharnes-attikis', prefecture: 'Αττικής' },
  { name: 'Αμπελόκηποι (Αθήνα)', slug: 'ampelokipoi-athina', prefecture: 'Αττικής' },
  { name: 'Αμφιθέα (Παλαιό Φάληρο Αττικής)', slug: 'amfithea-palaio-faliro-attikis', prefecture: 'Αττικής' },
  { name: 'Ανάβρυτα (Μαρούσι)', slug: 'anavryta-marousi', prefecture: 'Αττικής' },
  { name: 'Ανάβυσσος', slug: 'anavyssos-attikis', prefecture: 'Αττικής' },
  { name: 'Αναγέννηση (Αιγάλεω Αττικής)', slug: 'anagennisi-aigaleo-attikis', prefecture: 'Αττικής' },
  { name: 'Ανάκασα (Άγιοι Ανάργυροι Αττικής)', slug: 'anakasa-agioi-anargyroi-attikis', prefecture: 'Αττικής' },
  { name: 'Ανάληψη (Βριλήσσια Αττικής)', slug: 'analipsi-vrilissia-attikis', prefecture: 'Αττικής' },
  { name: 'Ανάληψη (Βύρωνας Αττικής)', slug: 'analipsi-vyronas-attikis', prefecture: 'Αττικής' },
  { name: 'Αναπήρων (Άλιμος Αττικής)', slug: 'anapiron-alimos-attikis', prefecture: 'Αττικής' },
  { name: 'Ανατολικά Προάστια Αθήνας', slug: 'anatolika-proastia-athinas', prefecture: 'Αττικής' },
  { name: 'Ανθέων (Άγιος Δημήτριος Αττικής)', slug: 'antheon-agios-dimitrios-attikis', prefecture: 'Αττικής' },
  { name: 'Ανθοκηπουροί (Καματερό Αττικής)', slug: 'anthokipouroi-kamatero-attikis', prefecture: 'Αττικής' },
  { name: 'Ανθούπολη (Περιστέρι Αττικής)', slug: 'anthoupoli-peristeri-attikis', prefecture: 'Αττικής' },
  { name: 'Άνοιξη', slug: 'anoixi-attikis', prefecture: 'Αττικής' },
  { name: 'Άνω Ανάκασα (Άγιοι Ανάργυροι Αττικής)', slug: 'ano-anakasa-agioi-anargyroi-attikis', prefecture: 'Αττικής' },
  { name: 'Άνω Ανθούπολη - Αγία Μαρίνα (Περιστέρι Αττικής)', slug: 'ano-anthoupoli-agia-marina-peristeri-attikis', prefecture: 'Αττικής' },
  { name: 'Άνω Άνοιξη (Άνοιξη - Άγιος Στέφανος - Σταμάτα)', slug: 'ano-anoixi-anoixi-agios-stefanos-stamata', prefecture: 'Αττικής' },
  { name: 'Άνω Αργυρούπολη (Αργυρούπολη Αττικής)', slug: 'ano-argyroupoli-argyroupoli-attikis', prefecture: 'Αττικής' },
  { name: 'Άνω Βούλα (Βούλα Αττικής)', slug: 'ano-voula-voula-attikis', prefecture: 'Αττικής' },
  { name: 'Άνω Βουλιαγμένη - Φανερωμένη (Βουλιαγμένη Αττικής)', slug: 'ano-vouliagmeni-faneromeni-vouliagmeni-attikis', prefecture: 'Αττικής' },
  { name: 'Άνω Βριλήσσια (Βριλήσσια Αττικής)', slug: 'ano-vrilissia-vrilissia-attikis', prefecture: 'Αττικής' },
  { name: 'Άνω Γλυφάδα (Γλυφάδα Αττικής)', slug: 'ano-glyfada-glyfada-attikis', prefecture: 'Αττικής' },
  { name: 'Άνω Δάφνη (Δάφνη Αττικής)', slug: 'ano-dafni-dafni-attikis', prefecture: 'Αττικής' },
  { name: 'Άνω Δροσιά (Δροσιά Αττικής)', slug: 'ano-drosia-drosia-attikis', prefecture: 'Αττικής' },
  { name: 'Άνω Ελευσίνα (Ελευσίνα Αττικής)', slug: 'ano-elefsina-elefsina-attikis', prefecture: 'Αττικής' },
  { name: 'Άνω Ζεφύρι (Ζεφύρι Αττικής)', slug: 'ano-zefyri-zefyri-attikis', prefecture: 'Αττικής' },
  { name: 'Άνω Ηλιούπολη (Ηλιούπολη Αττικής)', slug: 'ano-ilioupoli-ilioupoli-attikis', prefecture: 'Αττικής' },
  { name: 'Άνω Ιλίσια (Ζωγράφος Αττικής)', slug: 'ano-ilisia-zografos-attikis', prefecture: 'Αττικής' },
  { name: 'Άνω Καισαριανή (Καισαριανή Αττικής)', slug: 'ano-kaisariani-kaisariani-attikis', prefecture: 'Αττικής' },
  { name: 'Άνω Κόκκινος Μύλος (Αχαρνές Αττικής)', slug: 'ano-kokkinos-mylos-acharnes-attikis', prefecture: 'Αττικής' },
  { name: 'Άνω Κυψέλη (Αθήνα - Γαλάτσι)', slug: 'ano-kypseli-athina-galatsi', prefecture: 'Αττικής' },
  { name: 'Άνω Λιόσια', slug: 'ano-liosia-attikis', prefecture: 'Αττικής' },
  { name: 'Άνω Λόφος (Περιστέρι - Χαϊδάρι)', slug: 'ano-lofos-peristeri-chaidari', prefecture: 'Αττικής' },
  { name: 'Άνω Μελίσσια (Μελίσσια Αττικής)', slug: 'ano-melissia-melissia-attikis', prefecture: 'Αττικής' },
  { name: 'Άνω Νέα Σμύρνη (Νέα Σμύρνη - Άγιος Δημήτριος)', slug: 'ano-nea-smyrni-nea-smyrni-agios-dimitrios', prefecture: 'Αττικής' },
  { name: 'Άνω Παπάγος (Παπάγος Αττικής)', slug: 'ano-papagos-papagos-attikis', prefecture: 'Αττικής' },
  { name: 'Άνω Πατήσια (Αθήνα)', slug: 'ano-patisia-athina', prefecture: 'Αττικής' },
  { name: 'Άνω Πετράλωνα (Αθήνα)', slug: 'ano-petralona-athina', prefecture: 'Αττικής' },
  { name: 'Άνω Πετρούπολη (Πετρούπολη Αττικής)', slug: 'ano-petroupoli-petroupoli-attikis', prefecture: 'Αττικής' },
  { name: 'Άνω Πεύκη (Πεύκη - Μαρούσι)', slug: 'ano-peyki-peyki-marousi', prefecture: 'Αττικής' },
  { name: 'Άνω Φάληρο (Παλαιό Φάληρο Αττικής)', slug: 'ano-faliro-palaio-faliro-attikis', prefecture: 'Αττικής' },
  { name: 'Άνω Φιλοθέη (Φιλοθέη - Ψυχικό)', slug: 'ano-filothei-filothei-psychiko', prefecture: 'Αττικής' },
  { name: 'Άνω Χαλάνδρι (Χαλάνδρι Αττικής)', slug: 'ano-chalandri-chalandri-attikis', prefecture: 'Αττικής' },
  { name: 'Άνω Χολαργός (Χολαργός Αττικής)', slug: 'ano-cholargos-cholargos-attikis', prefecture: 'Αττικής' },
  { name: 'Αργοσαρωνικός', slug: 'argosaronikos', prefecture: 'Αττικής' },
  { name: 'Αργυρούπολη', slug: 'argyroupoli-attikis', prefecture: 'Αττικής' },
  { name: 'Αρτέμιδα Αττικής', slug: 'artemida-attikis', prefecture: 'Αττικής' },
  { name: 'Αρχαίος Δήμος (Πεντέλη Αττικής)', slug: 'archaios-dimos-penteli-attikis', prefecture: 'Αττικής' },
  { name: 'Άσπρα Χώματα (Περιστέρι Αττικής)', slug: 'aspra-chomata-peristeri-attikis', prefecture: 'Αττικής' },
  { name: 'Ασπρόπυργος', slug: 'aspropyrgos-attikis', prefecture: 'Αττικής' },
  { name: 'Αστεροσκοπείο (Πεντέλη Αττικής)', slug: 'asteroskopeio-penteli-attikis', prefecture: 'Αττικής' },
  { name: 'Αστυθέα (Χαϊδάρι Αττικής)', slug: 'astythea-chaidari-attikis', prefecture: 'Αττικής' },
  { name: 'Ασύρματος (Άγιος Δημήτριος Αττικής)', slug: 'asyrmatos-agios-dimitrios-attikis', prefecture: 'Αττικής' },
  { name: 'Αφίδνες Αττικής', slug: 'afidnes-attikis', prefecture: 'Αττικής' },
  { name: 'Βάρη', slug: 'vari-attikis', prefecture: 'Αττικής' },
  { name: 'Βάρκιζα (Βάρη Αττικής)', slug: 'varkiza-vari-attikis', prefecture: 'Αττικής' },
  { name: 'Βιαμάξ (Περιστέρι Αττικής)', slug: 'viamax-peristeri-attikis', prefecture: 'Αττικής' },
  { name: 'Βόρεια Προάστια Αθήνας', slug: 'voreia-proastia-athinas', prefecture: 'Αττικής' },
  { name: 'Βορινέζα (Αρτέμιδα Αττικής)', slug: 'vorineza-artemida-attikis', prefecture: 'Αττικής' },
  { name: 'Βοτανικός (Αθήνα - Αιγάλεω - Ταύρος)', slug: 'votanikos-athina-aigaleo-tayros', prefecture: 'Αττικής' },
  { name: 'Βούλα', slug: 'voula-attikis', prefecture: 'Αττικής' },
  { name: 'Βουλιαγμένη Αττικής', slug: 'vouliagmeni-attikis', prefecture: 'Αττικής' },
  { name: 'Βριλήσσια', slug: 'vrilissia-attikis', prefecture: 'Αττικής' },
  { name: 'Βύρωνας', slug: 'vyronas-attikis', prefecture: 'Αττικής' },
  { name: 'Γαλατάς Τροιζηνίας', slug: 'galatas-troizinias', prefecture: 'Αττικής' },
  { name: 'Γαλάτσι', slug: 'galatsi-attikis', prefecture: 'Αττικής' },
  { name: 'Γαργηττός (Γέρακας - Χαλάνδρι - Αγία Παρασκευή)', slug: 'gargittos-gerakas-chalandri-agia-paraskevi', prefecture: 'Αττικής' },
  { name: 'Γέρακας', slug: 'gerakas-attikis', prefecture: 'Αττικής' },
  { name: 'Γεροβουνό (Καματερό - Αχαρνές)', slug: 'gerovouno-kamatero-acharnes', prefecture: 'Αττικής' },
  { name: 'Γέφυρα - Γκουλιουμές (Αχαρνές Αττικής)', slug: 'gefyra-gkoulioumes-acharnes-attikis', prefecture: 'Αττικής' },
  { name: 'Γήπεδο Πανιωνίου (Νέα Σμύρνη Αττικής)', slug: 'gipedo-panioniou-nea-smyrni-attikis', prefecture: 'Αττικής' },
  { name: 'Γηροκομείο (Αθήνα)', slug: 'girokomeio-athina', prefecture: 'Αττικής' },
  { name: 'Γκάζι (Αθήνα)', slug: 'gkazi-athina', prefecture: 'Αττικής' },
  { name: 'Γκύζη (Αθήνα)', slug: 'gkyzi-athina', prefecture: 'Αττικής' },
  { name: 'Γλυκά Νερά', slug: 'glyka-nera-attikis', prefecture: 'Αττικής' },
  { name: 'Γλυφάδα', slug: 'glyfada-attikis', prefecture: 'Αττικής' },
  { name: 'Γουδή (Ζωγράφος - Αθήνα)', slug: 'goudi-zografos-athina', prefecture: 'Αττικής' },
  { name: 'Δάσος (Χαϊδάρι Αττικής)', slug: 'dasos-chaidari-attikis', prefecture: 'Αττικής' },
  { name: 'Δάφνη', slug: 'dafni-attikis', prefecture: 'Αττικής' },
  { name: 'Δέλτα Φαλήρου (Παλαιό Φάληρο - Καλλιθέα)', slug: 'delta-falirou-palaio-faliro-kallithea', prefecture: 'Αττικής' },
  { name: 'Δεξαμενή (Νέα Πεντέλη Αττικής)', slug: 'dexameni-nea-penteli-attikis', prefecture: 'Αττικής' },
  { name: 'Δικηγορικά (Βούλα Αττικής)', slug: 'dikigorika-voula-attikis', prefecture: 'Αττικής' },
  { name: 'Δόξα (Αγία Βαρβάρα Αττικής)', slug: 'doxa-agia-varvara-attikis', prefecture: 'Αττικής' },
  { name: 'Δροσιά Αττικής', slug: 'drosia-attikis', prefecture: 'Αττικής' },
  { name: 'Δυτικά Προάστια Αθήνας', slug: 'dytika-proastia-athinas', prefecture: 'Αττικής' },
  { name: 'Εκτελωνιστών (Άλιμος Αττικής)', slug: 'ekteloniston-alimos-attikis', prefecture: 'Αττικής' },
  { name: 'Ελαιώνας - Άνω Λιούμη (Χαϊδάρι Αττικής)', slug: 'elaionas-ano-lioumi-chaidari-attikis', prefecture: 'Αττικής' },
  { name: 'Ελαιώνας (Αθήνα - Αιγάλεω)', slug: 'elaionas-athina-aigaleo', prefecture: 'Αττικής' },
  { name: 'Ελευθερούπολη (Νέα Ιωνία Αττικής)', slug: 'eleftheroupoli-nea-ionia-attikis', prefecture: 'Αττικής' },
  { name: 'Ελευσίνα', slug: 'elefsina-attikis', prefecture: 'Αττικής' },
  { name: 'Ελληνικό', slug: 'elliniko-attikis', prefecture: 'Αττικής' },
  { name: 'Ελληνορώσων (Αθήνα - Νέο Ψυχικό)', slug: 'ellinoroson-athina-neo-psychiko', prefecture: 'Αττικής' },
  { name: 'Εμπορική και Βιομηχανική Περιοχή Θριασίου Πεδίου (Ασπρόπυργος Αττικής)', slug: 'emporiki-kai-viomichaniki-periochi-thriasiou-pediou-aspropyrgos-attikis', prefecture: 'Αττικής' },
  { name: 'Εξάρχεια (Αθήνα)', slug: 'exarcheia-athina', prefecture: 'Αττικής' },
  { name: 'Εργατικές Κατοικίες (Μαρούσι Αττικής)', slug: 'ergatikes-katoikies-marousi-attikis', prefecture: 'Αττικής' },
  { name: 'Εσταυρωμένος (Ταύρος Αττικής)', slug: 'estavromenos-tayros-attikis', prefecture: 'Αττικής' },
  { name: 'Ευαγγελισμός (Αθήνα)', slug: 'evangelismos-athina', prefecture: 'Αττικής' },
  { name: 'Ευαγγελίστρια (Νέα Ερυθραία Αττικής)', slug: 'evangelistria-nea-erythraia-attikis', prefecture: 'Αττικής' },
  { name: 'Ευαγγελίστρια (Νέα Ιωνία Αττικής)', slug: 'evangelistria-nea-ionia-attikis', prefecture: 'Αττικής' },
  { name: 'Ευαγγελίστρια (Περιστέρι Αττικής)', slug: 'evangelistria-peristeri-attikis', prefecture: 'Αττικής' },
  { name: 'Ευγενίας (Κερατσίνι Αττικής)', slug: 'evgenias-keratsini-attikis', prefecture: 'Αττικής' },
  { name: 'Ευρυάλη (Γλυφάδα Αττικής)', slug: 'evryali-glyfada-attikis', prefecture: 'Αττικής' },
  { name: 'Ζαφειρίου - Αγία Μαύρα (Νέα Ερυθραία Αττικής)', slug: 'zafeiriou-agia-mayra-nea-erythraia-attikis', prefecture: 'Αττικής' },
  { name: 'Ζεφύρι Αττικής', slug: 'zefyri-attikis', prefecture: 'Αττικής' },
  { name: 'Ζηρίνειο (Κηφισιά Αττικής)', slug: 'zirineio-kifisia-attikis', prefecture: 'Αττικής' },
  { name: 'Ζωγράφου', slug: 'zografos-attikis', prefecture: 'Αττικής' },
  { name: 'Ζωοδόχος Πηγή - Άνω Βύρωνας (Βύρωνας Αττικής)', slug: 'zoodochos-pigi-ano-vyronas-vyronas-attikis', prefecture: 'Αττικής' },
  { name: 'Ζωοδόχος Πηγή (Δάφνη Αττικής)', slug: 'zoodochos-pigi-dafni-attikis', prefecture: 'Αττικής' },
  { name: 'Ζωοδόχος Πηγή (Ίλιον)', slug: 'zoodochos-pigi-ilion', prefecture: 'Αττικής' },
  { name: 'Ζωοδόχος Πηγή (Λυκόβρυση Αττικής)', slug: 'zoodochos-pigi-lykovrysi-attikis', prefecture: 'Αττικής' },
  { name: 'Ζωοδόχος Πηγή (Μελίσσια Αττικής)', slug: 'zoodochos-pigi-melissia-attikis', prefecture: 'Αττικής' },
  { name: 'Ζωφριά (Άνω Λιόσια Αττικής)', slug: 'zofria-ano-liosia-attikis', prefecture: 'Αττικής' },
  { name: 'Ηλιούπολη', slug: 'ilioupoli-attikis', prefecture: 'Αττικής' },
  { name: 'Ηπειρώτικα (Άγιος Δημήτριος Αττικής)', slug: 'ipeirotika-agios-dimitrios-attikis', prefecture: 'Αττικής' },
  { name: 'Ηράκλειο Αττικής', slug: 'irakleio-attikis', prefecture: 'Αττικής' },
  { name: 'Θρακομακεδόνες Αττικής', slug: 'thrakomakedones-attikis', prefecture: 'Αττικής' },
  { name: 'Θυμαράκια (Αθήνα)', slug: 'thymarakia-athina', prefecture: 'Αττικής' },
  { name: 'Ιεράπολη (Αιγάλεω Αττικής)', slug: 'ierapoli-aigaleo-attikis', prefecture: 'Αττικής' },
  { name: 'Ικαριώτικα - Προφήτης Ηλίας (Πέραμα Αττικής)', slug: 'ikariotika-profitis-ilias-perama-attikis', prefecture: 'Αττικής' },
  { name: 'Ίλιον', slug: 'ilion-attikis', prefecture: 'Αττικής' },
  { name: 'Ιλίσια (Αθήνα - Ζωγράφος)', slug: 'ilisia-athina-zografos', prefecture: 'Αττικής' },
  { name: 'Καισαριανή', slug: 'kaisariani-attikis', prefecture: 'Αττικής' },
  { name: 'Καλαμάκι', slug: 'kalamaki-attikis', prefecture: 'Αττικής' },
  { name: 'Κάλαμος Αττικής', slug: 'kalamos-attikis', prefecture: 'Αττικής' },
  { name: 'Καλλιθέα', slug: 'kallithea-attikis', prefecture: 'Αττικής' },
  { name: 'Καλογρέζα (Νέα Ιωνία Αττικής)', slug: 'kalogreza-nea-ionia-attikis', prefecture: 'Αττικής' },
  { name: 'Καλύβια Θορικού', slug: 'kalyvia-thorikou-attikis', prefecture: 'Αττικής' },
  { name: 'Καλυκοποιείο (Υμηττός Αττικής)', slug: 'kalykopoieio-ymittos-attikis', prefecture: 'Αττικής' },
  { name: 'Καματερό', slug: 'kamatero-attikis', prefecture: 'Αττικής' },
  { name: 'Καναπίτσα (Μεταμόρφωση - Ηράκλειο)', slug: 'kanapitsa-metamorfosi-irakleio', prefecture: 'Αττικής' },
  { name: 'Κάντζα (Λεοντάρι Αττικής)', slug: 'kantza-leontari-attikis', prefecture: 'Αττικής' },
  { name: 'Καπανδρίτι', slug: 'kapandriti-attikis', prefecture: 'Αττικής' },
  { name: 'Καραγιανναίικα (Γαλάτσι Αττικής)', slug: 'karagiannaiika-galatsi-attikis', prefecture: 'Αττικής' },
  { name: 'Καρακάλεζι - Χαμόστερνα (Αχαρνές Αττικής)', slug: 'karakalezi-chamosterna-acharnes-attikis', prefecture: 'Αττικής' },
  { name: 'Καραπάνου (Γλυφάδα Αττικής)', slug: 'karapanou-glyfada-attikis', prefecture: 'Αττικής' },
  { name: 'Καρέας (Βύρωνας - Ηλιούπολη)', slug: 'kareas-vyronas-ilioupoli', prefecture: 'Αττικής' },
  { name: 'Κατεβασιά (Αχαρνές Αττικής)', slug: 'katevasia-acharnes-attikis', prefecture: 'Αττικής' },
  { name: 'Κάτω Αιγάλεω - Εσταυρωμένου (Αιγάλεω Αττικής)', slug: 'kato-aigaleo-estavromenou-aigaleo-attikis', prefecture: 'Αττικής' },
  { name: 'Κάτω Άνοιξη (Άνοιξη - Σταμάτα)', slug: 'kato-anoixi-anoixi-stamata', prefecture: 'Αττικής' },
  { name: 'Κάτω Ασπρόπυργος (Ασπρόπυργος Αττικής)', slug: 'kato-aspropyrgos-aspropyrgos-attikis', prefecture: 'Αττικής' },
  { name: 'Κάτω Βούλα (Βούλα Αττικής)', slug: 'kato-voula-voula-attikis', prefecture: 'Αττικής' },
  { name: 'Κάτω Βουλιαγμένη - Άγιος Παντελεήμονας (Βουλιαγμένη Αττικής)', slug: 'kato-vouliagmeni-agios-panteleimonas-vouliagmeni-attikis', prefecture: 'Αττικής' },
  { name: 'Κάτω Ελευσίνα (Ελευσίνα Αττικής)', slug: 'kato-elefsina-elefsina-attikis', prefecture: 'Αττικής' },
  { name: 'Κάτω Ευρυάλη (Βούλα Αττικής)', slug: 'kato-evryali-voula-attikis', prefecture: 'Αττικής' },
  { name: 'Κάτω Ηλιούπολη (Ηλιούπολη Αττικής)', slug: 'kato-ilioupoli-ilioupoli-attikis', prefecture: 'Αττικής' },
  { name: 'Κάτω Κηπούπολη (Περιστέρι Αττικής)', slug: 'kato-kipoupoli-peristeri-attikis', prefecture: 'Αττικής' },
  { name: 'Κάτω Κηφισιά (Κηφισιά Αττικής)', slug: 'kato-kifisia-kifisia-attikis', prefecture: 'Αττικής' },
  { name: 'Κάτω Μελίσσια (Μελίσσια Αττικής)', slug: 'kato-melissia-melissia-attikis', prefecture: 'Αττικής' },
  { name: 'Κάτω Πατήσια (Αθήνα)', slug: 'kato-patisia-athina', prefecture: 'Αττικής' },
  { name: 'Κάτω Πετράλωνα (Αθήνα)', slug: 'kato-petralona-athina', prefecture: 'Αττικής' },
  { name: 'Κάτω Πετρούπολη (Ίλιον - Πετρούπολη)', slug: 'kato-petroupoli-ilion-petroupoli', prefecture: 'Αττικής' },
  { name: 'Κάτω Πεύκη (Πεύκη - Ηράκλειο)', slug: 'kato-peyki-peyki-irakleio', prefecture: 'Αττικής' },
  { name: 'Κάτω Σταμάτα - Σπάτα (Σταμάτα Αττικής)', slug: 'kato-stamata-spata-stamata-attikis', prefecture: 'Αττικής' },
  { name: 'Κάτω Χαλάνδρι (Χαλάνδρι Αττικής)', slug: 'kato-chalandri-chalandri-attikis', prefecture: 'Αττικής' },
  { name: 'Κάτω Χολαργός (Χολαργός Αττικής)', slug: 'kato-cholargos-cholargos-attikis', prefecture: 'Αττικής' },
  { name: 'Κέντρο (Γέρακας Αττικής)', slug: 'kentro-gerakas-attikis', prefecture: 'Αττικής' },
  { name: 'Κέντρο (Μαρούσι Αττικής)', slug: 'kentro-marousi-attikis', prefecture: 'Αττικής' },
  { name: 'Κέντρο (Μεταμόρφωση Αττικής)', slug: 'kentro-metamorfosi-attikis', prefecture: 'Αττικής' },
  { name: 'Κέντρο (Παιανία Αττικής)', slug: 'kentro-paiania-attikis', prefecture: 'Αττικής' },
  { name: 'Κέντρο (Παλλήνη Αττικής)', slug: 'kentro-pallini-attikis', prefecture: 'Αττικής' },
  { name: 'Κέντρο (Ραφήνα Αττικής)', slug: 'kentro-rafina-attikis', prefecture: 'Αττικής' },
  { name: 'Κέντρο (Χαλάνδρι Αττικής)', slug: 'kentro-chalandri-attikis', prefecture: 'Αττικής' },
  { name: 'Κεραμεικός (Αθήνα)', slug: 'kerameikos-athina', prefecture: 'Αττικής' },
  { name: 'Κερατέα', slug: 'keratea-attikis', prefecture: 'Αττικής' },
  { name: 'Κερατσίνι', slug: 'keratsini-attikis', prefecture: 'Αττικής' },
  { name: 'Κεφαλάρι (Κηφισιά Αττικής)', slug: 'kefalari-kifisia-attikis', prefecture: 'Αττικής' },
  { name: 'Κεφαλλήνων (Άλιμος Αττικής)', slug: 'kefallinon-alimos-attikis', prefecture: 'Αττικής' },
  { name: 'Κηπούπολη - Νησάκι (Πετρούπολη - Ίλιον)', slug: 'kipoupoli-nisaki-petroupoli-ilion', prefecture: 'Αττικής' },
  { name: 'Κηφισιά', slug: 'kifisia-attikis', prefecture: 'Αττικής' },
  { name: 'Κοκκιναράς (Κηφισιά Αττικής)', slug: 'kokkinaras-kifisia-attikis', prefecture: 'Αττικής' },
  { name: 'Κοκκινιά (Μαρούσι)', slug: 'kokkinia-marousi', prefecture: 'Αττικής' },
  { name: 'Κόκκινος Μύλος (Νέα Φιλαδέλφεια - Αχαρνές)', slug: 'kokkinos-mylos-nea-filadelfeia-acharnes', prefecture: 'Αττικής' },
  { name: 'Κολοκυνθού (Αθήνα - Περιστέρι)', slug: 'kolokynthou-athina-peristeri', prefecture: 'Αττικής' },
  { name: 'Κολωνάκι (Αθήνα)', slug: 'kolonaki-athina', prefecture: 'Αττικής' },
  { name: 'Κολωνός (Αθήνα)', slug: 'kolonos-athina', prefecture: 'Αττικής' },
  { name: 'Κοντόπευκο (Αγία Παρασκευή - Χαλάνδρι)', slug: 'kontopefko-agia-paraskevi-chalandri', prefecture: 'Αττικής' },
  { name: 'Κοντοχέρι - Σταυράμπολη (Αχαρνές Αττικής)', slug: 'kontocheri-stavrampoli-acharnes-attikis', prefecture: 'Αττικής' },
  { name: 'Κοπρίσια - Κουκουβάουνες (Μεταμόρφωση Αττικής)', slug: 'koprisia-koukouvaounes-metamorfosi-attikis', prefecture: 'Αττικής' },
  { name: 'Κορωπί', slug: 'koropi-attikis', prefecture: 'Αττικής' },
  { name: 'Κουκάκι (Αθήνα)', slug: 'koukaki-athina', prefecture: 'Αττικής' },
  { name: 'Κουνέλια (Χαϊδάρι Αττικής)', slug: 'kounelia-chaidari-attikis', prefecture: 'Αττικής' },
  { name: 'Κουντουριώτικα (Αθήνα)', slug: 'kountouriotika-athina', prefecture: 'Αττικής' },
  { name: 'Κρητικά (Γαλάτσι Αττικής)', slug: 'kritika-galatsi-attikis', prefecture: 'Αττικής' },
  { name: 'Κυθηρίων - Πανί (Άλιμος Αττικής)', slug: 'kythirion-pani-alimos-attikis', prefecture: 'Αττικής' },
  { name: 'Κυνοσάργους (Αθήνα)', slug: 'kynosargous-athina', prefecture: 'Αττικής' },
  { name: 'Κυπριάδου (Αθήνα)', slug: 'kypriadou-athina', prefecture: 'Αττικής' },
  { name: 'Κυψέλη (Αθήνα)', slug: 'kypseli-athina', prefecture: 'Αττικής' },
  { name: 'Λαζάρου - Άγιος Κωνσταντίνος (Νέα Ιωνία - Νέα Φιλαδέλφεια)', slug: 'lazarou-agios-konstantinos-nea-ionia-nea-filadelfeia', prefecture: 'Αττικής' },
  { name: 'Λαθέα - Αγία Τριάδα (Αχαρνές Αττικής)', slug: 'lathea-agia-triada-acharnes-attikis', prefecture: 'Αττικής' },
  { name: 'Λαμπρινή (Γαλάτσι - Αθήνα)', slug: 'lamprini-galatsi-athina', prefecture: 'Αττικής' },
  { name: 'Λαύριο', slug: 'layrio-attikis', prefecture: 'Αττικής' },
  { name: 'Λεοντάρι Αττικής', slug: 'leontari-attikis', prefecture: 'Αττικής' },
  { name: 'Λεόντειος (Νέα Σμύρνη Αττικής)', slug: 'leonteios-nea-smyrni-attikis', prefecture: 'Αττικής' },
  { name: 'Λιμένας Μαρκοπούλου Αττικής', slug: 'limenas-markopoulou-attikis', prefecture: 'Αττικής' },
  { name: 'Λιούμη (Αιγάλεω Αττικής)', slug: 'lioumi-aigaleo-attikis', prefecture: 'Αττικής' },
  { name: 'Λόγγος (Μεταμόρφωση Αττικής)', slug: 'longos-metamorfosi-attikis', prefecture: 'Αττικής' },
  { name: 'Λούτσα (Αρτέμιδα Αττικής)', slug: 'loutsa-artemida-attikis', prefecture: 'Αττικής' },
  { name: 'Λόφος Αξιωματικών (Περιστέρι Αττικής)', slug: 'lofos-axiomatikon-peristeri-attikis', prefecture: 'Αττικής' },
  { name: 'Λόφος Σκουζέ (Αθήνα)', slug: 'lofos-skouze-athina', prefecture: 'Αττικής' },
  { name: 'Λόφος Φιλαρέτου (Καλλιθέα Αττικής)', slug: 'lofos-filaretou-kallithea-attikis', prefecture: 'Αττικής' },
  { name: 'Λυκαβηττός (Αθήνα)', slug: 'lykavittos-athina', prefecture: 'Αττικής' },
  { name: 'Λυκόβρυση', slug: 'lykovrysi-attikis', prefecture: 'Αττικής' },
  { name: 'Λυκομπούτι (Αρτέμιδα Αττικής)', slug: 'lykompouti-artemida-attikis', prefecture: 'Αττικής' },
  { name: 'Λυκότρυπα (Αχαρνές Αττικής)', slug: 'lykotrypa-acharnes-attikis', prefecture: 'Αττικής' },
  { name: 'Μακρυγιάννη (Αγία Βαρβάρα Αττικής)', slug: 'makrygianni-agia-varvara-attikis', prefecture: 'Αττικής' },
  { name: 'Μάνδρα', slug: 'mandra-attikis', prefecture: 'Αττικής' },
  { name: 'Μαραθώνας', slug: 'marathonas-attikis', prefecture: 'Αττικής' },
  { name: 'Μαρκόπουλο Μεσογαίας', slug: 'markopoulo-mesogaias-attikis', prefecture: 'Αττικής' },
  { name: 'Μαρκόπουλο Ωρωπού Αττικής', slug: 'markopoulo-oropou-attikis', prefecture: 'Αττικής' },
  { name: 'Μαρούσι', slug: 'marousi-attikis', prefecture: 'Αττικής' },
  { name: 'Μάσχα (Περιστέρι Αττικής)', slug: 'mascha-peristeri-attikis', prefecture: 'Αττικής' },
  { name: 'Μέγαρα', slug: 'megara-attikis', prefecture: 'Αττικής' },
  { name: 'Μελίσσια', slug: 'melissia-attikis', prefecture: 'Αττικής' },
  { name: 'Μενίδι', slug: 'acharnes-attikis', prefecture: 'Αττικής' },
  { name: 'Μενιδιάτικα (Γαλάτσι Αττικής)', slug: 'menidiatika-galatsi-attikis', prefecture: 'Αττικής' },
  { name: 'Μεταμόρφωση (Βύρωνας Αττικής)', slug: 'metamorfosi-vyronas-attikis', prefecture: 'Αττικής' },
  { name: 'Μεταμόρφωση Αττικής', slug: 'metamorfosi-attikis', prefecture: 'Αττικής' },
  { name: 'Μεταξουργείο (Αθήνα)', slug: 'metaxourgeio-athina', prefecture: 'Αττικής' },
  { name: 'Μιχελή (Ίλιον)', slug: 'micheli-ilion', prefecture: 'Αττικής' },
  { name: 'Μοναστηράκι (Αθήνα)', slug: 'monastiraki-athina', prefecture: 'Αττικής' },
  { name: 'Μορτερό (Νέα Ερυθραία Αττικής)', slug: 'mortero-nea-erythraia-attikis', prefecture: 'Αττικής' },
  { name: 'Μουσείο (Αθήνα)', slug: 'mouseio-athina', prefecture: 'Αττικής' },
  { name: 'Μπαλάνα (Γέρακας - Παλλήνη)', slug: 'balana-gerakas-pallini', prefecture: 'Αττικής' },
  { name: 'Μπουρνάζι (Περιστέρι - Ίλιον)', slug: 'bournazi-peristeri-ilion', prefecture: 'Αττικής' },
  { name: 'Μποφίλια - Νέα Ζωή - Βλάχος (Μεταμόρφωση - Αχαρνές)', slug: 'bofilia-nea-zoi-vlachos-metamorfosi-acharnes', prefecture: 'Αττικής' },
  { name: 'Μυκονιάτικα (Άγιοι Ανάργυροι Αττικής)', slug: 'mykoniatika-agioi-anargyroi-attikis', prefecture: 'Αττικής' },
  { name: 'Μυτιληναίικα (Νέα Σμύρνη Αττικής)', slug: 'mytilinaiika-nea-smyrni-attikis', prefecture: 'Αττικής' },
  { name: 'Νέα Αγορά (Ψυχικό Αττικής)', slug: 'nea-agora-psychiko-attikis', prefecture: 'Αττικής' },
  { name: 'Νέα Ελβετία (Βύρωνας Αττικής)', slug: 'nea-elvetia-vyronas-attikis', prefecture: 'Αττικής' },
  { name: 'Νέα Ερυθραία', slug: 'nea-erythraia-attikis', prefecture: 'Αττικής' },
  { name: 'Νέα Ευρυάλη (Γλυφάδα Αττικής)', slug: 'nea-evryali-glyfada-attikis', prefecture: 'Αττικής' },
  { name: 'Νέα Ζωή (Αγία Παρασκευή Αττικής)', slug: 'nea-zoi-agia-paraskevi-attikis', prefecture: 'Αττικής' },
  { name: 'Νέα Ζωή (Περιστέρι Αττικής)', slug: 'nea-zoi-peristeri-attikis', prefecture: 'Αττικής' },
  { name: 'Νέα Ιωνία', slug: 'nea-ionia-attikis', prefecture: 'Αττικής' },
  { name: 'Νέα Κάλυμνος (Βούλα Αττικής)', slug: 'nea-kalymnos-voula-attikis', prefecture: 'Αττικής' },
  { name: 'Νέα Κηφισιά (Κηφισιά Αττικής)', slug: 'nea-kifisia-kifisia-attikis', prefecture: 'Αττικής' },
  { name: 'Νέα Κυψέλη (Αθήνα)', slug: 'nea-kypseli-athina', prefecture: 'Αττικής' },
  { name: 'Νέα Λέσβος - Αγγελοπούλου (Μαρούσι)', slug: 'nea-lesvos-angelopoulou-marousi', prefecture: 'Αττικής' },
  { name: 'Νέα Μάδυτος - Άγιος Ιωάννης (Νέα Φιλαδέλφεια Αττικής)', slug: 'nea-madytos-agios-ioannis-nea-filadelfeia-attikis', prefecture: 'Αττικής' },
  { name: 'Νέα Μάκρη', slug: 'nea-makri-attikis', prefecture: 'Αττικής' },
  { name: 'Νέα Ολυμπία (Καματερό Αττικής)', slug: 'nea-olympia-kamatero-attikis', prefecture: 'Αττικής' },
  { name: 'Νέα Παλάτια Αττικής', slug: 'nea-palatia-attikis', prefecture: 'Αττικής' },
  { name: 'Νέα Πεντέλη Αττικής', slug: 'nea-penteli-attikis', prefecture: 'Αττικής' },
  { name: 'Νέα Πέραμος', slug: 'nea-peramos-attikis', prefecture: 'Αττικής' },
  { name: 'Νέα Σμύρνη', slug: 'nea-smyrni-attikis', prefecture: 'Αττικής' },
  { name: 'Νέα Φιλαδέλφεια', slug: 'nea-filadelfeia-attikis', prefecture: 'Αττικής' },
  { name: 'Νέα Φιλοθέη (Αθήνα - Ψυχικό)', slug: 'nea-filothei-athina-psychiko', prefecture: 'Αττικής' },
  { name: 'Νέα Φιλοθέη (Μαρούσι - Νέα Ιωνία)', slug: 'nea-filothei-marousi-nea-ionia', prefecture: 'Αττικής' },
  { name: 'Νέα Χαλκηδόνα', slug: 'nea-chalkidona-attikis', prefecture: 'Αττικής' },
  { name: 'Νεάπολη (Αθήνα)', slug: 'neapoli-athina', prefecture: 'Αττικής' },
  { name: 'Νεάπολη (Αχαρνές Αττικής)', slug: 'neapoli-acharnes-attikis', prefecture: 'Αττικής' },
  { name: 'Νεάπολη (Νέα Ιωνία Αττικής)', slug: 'neapoli-nea-ionia-attikis', prefecture: 'Αττικής' },
  { name: 'Νέο Αιγάλεω (Αιγάλεω Αττικής)', slug: 'neo-aigaleo-aigaleo-attikis', prefecture: 'Αττικής' },
  { name: 'Νέο Ηράκλειο (Ηράκλειο Αττικής)', slug: 'neo-irakleio-irakleio-attikis', prefecture: 'Αττικής' },
  { name: 'Νέο Μαρούσι (Μαρούσι Αττικής)', slug: 'neo-marousi-marousi-attikis', prefecture: 'Αττικής' },
  { name: 'Νέο Παγκράτι (Βύρωνας Αττικής)', slug: 'neo-pagkrati-vyronas-attikis', prefecture: 'Αττικής' },
  { name: 'Νέο Τέρμα (Μαρούσι)', slug: 'neo-terma-marousi', prefecture: 'Αττικής' },
  { name: 'Νέο Χαλάνδρι (Χαλάνδρι Αττικής)', slug: 'neo-chalandri-chalandri-attikis', prefecture: 'Αττικής' },
  { name: 'Νέο Ψυχικό', slug: 'neo-psychiko-attikis', prefecture: 'Αττικής' },
  { name: 'Νέος Βουτζάς Αττικής', slug: 'neos-voutzas-attikis', prefecture: 'Αττικής' },
  { name: 'Νέος Κόσμος (Αθήνα - Δάφνη)', slug: 'neos-kosmos-athina-dafni', prefecture: 'Αττικής' },
  { name: 'Νέος Πόντος (Ραφήνα - Νέος Βουτζάς)', slug: 'neos-pontos-rafina-neos-voutzas', prefecture: 'Αττικής' },
  { name: 'Νοσοκομείο Συγγρού (Καισαριανή - Αθήνα)', slug: 'nosokomeio-syngrou-kaisariani-athina', prefecture: 'Αττικής' },
  { name: 'Νότια Προάστια Αθήνας', slug: 'notia-proastia-athinas', prefecture: 'Αττικής' },
  { name: 'Νταμαράκια (Αιγάλεω Αττικής)', slug: 'ntamarakia-aigaleo-attikis', prefecture: 'Αττικής' },
  { name: 'Ομόνοια (Αθήνα)', slug: 'omonoia-athina', prefecture: 'Αττικής' },
  { name: 'Παγκράτι (Αθήνα)', slug: 'pagkrati-athina', prefecture: 'Αττικής' },
  { name: 'Παιανία', slug: 'paiania-attikis', prefecture: 'Αττικής' },
  { name: 'Παλαιά Φώκαια Αττικής', slug: 'palaia-fokaia-attikis', prefecture: 'Αττικής' },
  { name: 'Παλαιό Ηράκλειο (Ηράκλειο Κρήτης)', slug: 'palaio-irakleio-irakleio-kritis', prefecture: 'Αττικής' },
  { name: 'Παλαιό Μενίδι (Αχαρνές Αττικής)', slug: 'palaio-menidi-acharnes-attikis', prefecture: 'Αττικής' },
  { name: 'Παλαιό Φάληρο', slug: 'palaio-faliro-attikis', prefecture: 'Αττικής' },
  { name: 'Παλαιολόγου (Νέα Ιωνία Αττικής)', slug: 'palaiologou-nea-ionia-attikis', prefecture: 'Αττικής' },
  { name: 'Παλατάκι - Άγιος Γεώργιος (Χαϊδάρι Αττικής)', slug: 'palataki-agios-georgios-chaidari-attikis', prefecture: 'Αττικής' },
  { name: 'Παλιά Βουλή (Αθήνα)', slug: 'palia-vouli-athina', prefecture: 'Αττικής' },
  { name: 'Παλλήνη', slug: 'pallini-attikis', prefecture: 'Αττικής' },
  { name: 'Παλούκια (Σαλαμίνα - Αμπελάκια)', slug: 'paloukia-salamina-ampelakia', prefecture: 'Αττικής' },
  { name: 'Παναγία (Ηλιούπολη Αττικής)', slug: 'panagia-ilioupoli-attikis', prefecture: 'Αττικής' },
  { name: 'Παναγίτσα (Άγιος Δημήτριος Αττικής)', slug: 'panagitsa-agios-dimitrios-attikis', prefecture: 'Αττικής' },
  { name: 'Παναγίτσα (Αργυρούπολη Αττικής)', slug: 'panagitsa-argyroupoli-attikis', prefecture: 'Αττικής' },
  { name: 'Παναγίτσα (Καισαριανή Αττικής)', slug: 'panagitsa-kaisariani-attikis', prefecture: 'Αττικής' },
  { name: 'Παναγίτσα (Παλαιό Φάληρο Αττικής)', slug: 'panagitsa-palaio-faliro-attikis', prefecture: 'Αττικής' },
  { name: 'Πανιωνία (Γλυφάδα Αττικής)', slug: 'panionia-glyfada-attikis', prefecture: 'Αττικής' },
  { name: 'Πανόραμα (Αχαρνές - Θρακομακεδόνες)', slug: 'panorama-acharnes-thrakomakedones', prefecture: 'Αττικής' },
  { name: 'Πανόραμα (Ίλιον)', slug: 'panorama-ilion', prefecture: 'Αττικής' },
  { name: 'Παπάγου', slug: 'papagos-attikis', prefecture: 'Αττικής' },
  { name: 'Παράδεισος (Αγία Παρασκευή Αττικής)', slug: 'paradeisos-agia-paraskevi-attikis', prefecture: 'Αττικής' },
  { name: 'Παράδεισος (Μαρούσι - Χαλάνδρι)', slug: 'paradeisos-marousi-chalandri', prefecture: 'Αττικής' },
  { name: 'Παραρεμάτιος (Βριλήσσια Αττικής)', slug: 'pararematios-vrilissia-attikis', prefecture: 'Αττικής' },
  { name: 'Πάτημα (Αχαρνές Αττικής)', slug: 'patima-acharnes-attikis', prefecture: 'Αττικής' },
  { name: 'Πάτημα (Βριλήσσια Αττικής)', slug: 'patima-vrilissia-attikis', prefecture: 'Αττικής' },
  { name: 'Πάτημα (Χαλάνδρι - Γέρακας)', slug: 'patima-chalandri-gerakas', prefecture: 'Αττικής' },
  { name: 'Πειραιάς (Κέντρο - Δήμος)', slug: 'peiraias', prefecture: 'Αττικής' },
  { name: 'Πελοππονήσιοι (Κηφισιά Αττικής)', slug: 'pelopponisioi-kifisia-attikis', prefecture: 'Αττικής' },
  { name: 'Πεντέλη Αττικής', slug: 'penteli-attikis', prefecture: 'Αττικής' },
  { name: 'Πέραμα', slug: 'perama-attikis', prefecture: 'Αττικής' },
  { name: 'Περιβόλια (Γαλάτσι Αττικής)', slug: 'perivolia-galatsi-attikis', prefecture: 'Αττικής' },
  { name: 'Περισσός (Νέα Ιωνία Αττικής)', slug: 'perissos-nea-ionia-attikis', prefecture: 'Αττικής' },
  { name: 'Περιστέρι', slug: 'peristeri-attikis', prefecture: 'Αττικής' },
  { name: 'Πετρούπολη', slug: 'petroupoli-attikis', prefecture: 'Αττικής' },
  { name: 'Πευκάκια - Ινέπολη (Νέα Ιωνία - Νέα Φιλαδέλφεια)', slug: 'pefkakia-inepoli-nea-ionia-nea-filadelfeia', prefecture: 'Αττικής' },
  { name: 'Πευκάκια (Αθήνα)', slug: 'pefkakia-athina', prefecture: 'Αττικής' },
  { name: 'Πεύκη', slug: 'peyki-attikis', prefecture: 'Αττικής' },
  { name: 'Πηγαδάκια (Βούλα Αττικής)', slug: 'pigadakia-voula-attikis', prefecture: 'Αττικής' },
  { name: 'Πικέρμι', slug: 'pikermi-attikis', prefecture: 'Αττικής' },
  { name: 'Πλάκα (Αθήνα)', slug: 'plaka-athina', prefecture: 'Αττικής' },
  { name: 'Πλατεία Αμερικής (Αθήνα)', slug: 'plateia-amerikis-athina', prefecture: 'Αττικής' },
  { name: 'Πλατεία Άνοιξης (Νέα Σμύρνη Αττικής)', slug: 'plateia-anoixis-nea-smyrni-attikis', prefecture: 'Αττικής' },
  { name: 'Πλατεία Αττικής (Αθήνα)', slug: 'plateia-attikis-athina', prefecture: 'Αττικής' },
  { name: 'Πλατεία Βάθης (Αθήνα)', slug: 'plateia-vathis-athina', prefecture: 'Αττικής' },
  { name: 'Πλατεία Βικτωρίας (Αθήνα)', slug: 'plateia-viktorias-athina', prefecture: 'Αττικής' },
  { name: 'Πλατεία Κολιάτσου (Αθήνα)', slug: 'plateia-koliatsou-athina', prefecture: 'Αττικής' },
  { name: 'Πλατεία Κουμουνδούρου (Αθήνα)', slug: 'plateia-koumoundourou-athina', prefecture: 'Αττικής' },
  { name: 'Πλατεία Μαβίλη (Αθήνα)', slug: 'plateia-mavili-athina', prefecture: 'Αττικής' },
  { name: 'Πλατεία Ντάβαρη (Παλαιό Φάληρο Αττικής)', slug: 'plateia-ntavari-palaio-faliro-attikis', prefecture: 'Αττικής' },
  { name: 'Πλατεία Σταυριανού (Μεταμόρφωση Αττικής)', slug: 'plateia-stavrianou-metamorfosi-attikis', prefecture: 'Αττικής' },
  { name: 'Πλατεία Χρυσοστόμου Σμύρνης (Νέα Σμύρνη Αττικής)', slug: 'plateia-chrysostomou-smyrnis-nea-smyrni-attikis', prefecture: 'Αττικής' },
  { name: 'Πολιτεία (Βούλα Αττικής)', slug: 'politeia-voula-attikis', prefecture: 'Αττικής' },
  { name: 'Πολύγωνο (Αθήνα)', slug: 'polygono-athina', prefecture: 'Αττικής' },
  { name: 'Πολύδροσο (Μαρούσι Αττικής)', slug: 'polydroso-marousi-attikis', prefecture: 'Αττικής' },
  { name: 'Πολύδροσο (Χαλάνδρι Αττικής)', slug: 'polydroso-chalandri-attikis', prefecture: 'Αττικής' },
  { name: 'Πολυτέκνων (Ίλιον)', slug: 'polyteknon-ilion', prefecture: 'Αττικής' },
  { name: 'Πράσινος Λόφος (Ηράκλειο Αττικής)', slug: 'prasinos-lofos-irakleio-attikis', prefecture: 'Αττικής' },
  { name: 'Προμπονά (Αθήνα)', slug: 'prompona-athina', prefecture: 'Αττικής' },
  { name: 'Προσφυγικά (Καισαριανή)', slug: 'prosfygika-kaisariani', prefecture: 'Αττικής' },
  { name: 'Προφήτης Ηλίας (Αχαρνές Αττικής)', slug: 'profitis-ilias-acharnes-attikis', prefecture: 'Αττικής' },
  { name: 'Προφήτης Ηλίας (Νέα Πεντέλη Αττικής)', slug: 'profitis-ilias-nea-penteli-attikis', prefecture: 'Αττικής' },
  { name: 'Πυρνάρι (Γλυφάδα Αττικής)', slug: 'pyrnari-glyfada-attikis', prefecture: 'Αττικής' },
  { name: 'Ραφήνα', slug: 'rafina-attikis', prefecture: 'Αττικής' },
  { name: 'Ρέα (Δροσιά Αττικής)', slug: 'rea-drosia-attikis', prefecture: 'Αττικής' },
  { name: 'Ρέμα Χελιδονούς - Καλιφτάκη (Κηφισιά Αττικής)', slug: 'rema-chelidonous-kaliftaki-kifisia-attikis', prefecture: 'Αττικής' },
  { name: 'Ριζούπολη (Αθήνα - Νέα Ιωνία)', slug: 'rizoupoli-athina-nea-ionia', prefecture: 'Αττικής' },
  { name: 'Ριμινιτών - Ευαγγελίστρια (Ίλιον Αττικής)', slug: 'riminiton-evangelistria-ilion-attikis', prefecture: 'Αττικής' },
  { name: 'Ροδόπολη Αττικής', slug: 'rodopoli-attikis', prefecture: 'Αττικής' },
  { name: 'Σαλαμίνα (Χώρα)', slug: 'salamina', prefecture: 'Αττικής' },
  { name: 'Σαρωνίδα Αττικής', slug: 'saronida-attikis', prefecture: 'Αττικής' },
  { name: 'Σαρωνικός (Άγιος Δημήτριος Αττικής)', slug: 'saronikos-agios-dimitrios-attikis', prefecture: 'Αττικής' },
  { name: 'Σεπόλια (Αθήνα)', slug: 'sepolia-athina', prefecture: 'Αττικής' },
  { name: 'Σίδερα (Χαλάνδρι Αττικής)', slug: 'sidera-chalandri-attikis', prefecture: 'Αττικής' },
  { name: 'Σούλι (Άγιος Δημήτριος Αττικής)', slug: 'souli-agios-dimitrios-attikis', prefecture: 'Αττικής' },
  { name: 'Σούρμενα (Ελληνικό - Γλυφάδα)', slug: 'sourmena-elliniko-glyfada', prefecture: 'Αττικής' },
  { name: 'Σπάτα', slug: 'spata-attikis', prefecture: 'Αττικής' },
  { name: 'Σταμάτα Αττικής', slug: 'stamata-attikis', prefecture: 'Αττικής' },
  { name: 'Σταυρός (Γέρακας - Αγία Παρασκευή)', slug: 'stavros-gerakas-agia-paraskevi', prefecture: 'Αττικής' },
  { name: 'Σταυρός (Παλλήνη Αττικής)', slug: 'stavros-pallini-attikis', prefecture: 'Αττικής' },
  { name: 'Στροφύλι (Κηφισιά Αττικής)', slug: 'strofyli-kifisia-attikis', prefecture: 'Αττικής' },
  { name: 'Συκάμινο Αττικής', slug: 'sykamino-attikis', prefecture: 'Αττικής' },
  { name: 'Συνοικισμός Αναπήρων - Άγιοι Ανάργυροι (Νέα Ερυθραία Αττικής)', slug: 'synoikismos-anapiron-agioi-anargyroi-nea-erythraia-attikis', prefecture: 'Αττικής' },
  { name: 'Σύνταγμα (Αθήνα)', slug: 'syntagma-athina', prefecture: 'Αττικής' },
  { name: 'Σωρός (Μαρούσι)', slug: 'soros-marousi', prefecture: 'Αττικής' },
  { name: 'Ταμπούρια (Πειραιάς - Νίκαια)', slug: 'tampouria-peiraias-nikaia', prefecture: 'Αττικής' },
  { name: 'Ταύρος', slug: 'tayros-attikis', prefecture: 'Αττικής' },
  { name: 'Τερψιθέα (Γλυφάδα Αττικής)', slug: 'terpsithea-glyfada-attikis', prefecture: 'Αττικής' },
  { name: 'Τζιτζιφιές - Ιππόδρομος (Καλλιθέα Αττικής)', slug: 'tzitzifies-ippodromos-kallithea-attikis', prefecture: 'Αττικής' },
  { name: 'Τράχωνες (Άλιμος Αττικής)', slug: 'trachones-alimos-attikis', prefecture: 'Αττικής' },
  { name: 'Τρεις Γέφυρες (Αθήνα - Άγιοι Ανάργυροι)', slug: 'treis-gefyres-athina-agioi-anargyroi', prefecture: 'Αττικής' },
  { name: 'Τρίγωνο Αγίας Βαρβάρας (Χαλάνδρι Αττικής)', slug: 'trigono-agias-varvaras-chalandri-attikis', prefecture: 'Αττικής' },
  { name: 'Τσακός (Αγία Παρασκευή Αττικής)', slug: 'tsakos-agia-paraskevi-attikis', prefecture: 'Αττικής' },
  { name: 'Τσούμπα (Άγιοι Ανάργυροι Αττικής)', slug: 'tsoumpa-agioi-anargyroi-attikis', prefecture: 'Αττικής' },
  { name: 'Υμηττός', slug: 'ymittos-attikis', prefecture: 'Αττικής' },
  { name: 'Υπόλοιπο Αττικής', slug: 'ypoloipo-attikis', prefecture: 'Αττικής' },
  { name: 'Φανερωμένη (Χολαργός Αττικής)', slug: 'faneromeni-cholargos-attikis', prefecture: 'Αττικής' },
  { name: 'Φάρος Ψυχικού (Νέο Ψυχικό Αττικής)', slug: 'faros-psychikou-neo-psychiko-attikis', prefecture: 'Αττικής' },
  { name: 'Φιλοθέη Αττικής', slug: 'filothei-attikis', prefecture: 'Αττικής' },
  { name: 'Φλέβα (Ίλιον)', slug: 'fleva-ilion', prefecture: 'Αττικής' },
  { name: 'Φλοίσβος (Παλαιό Φάληρο Αττικής)', slug: 'floisvos-palaio-faliro-attikis', prefecture: 'Αττικής' },
  { name: 'Φούρεσι (Γλυκά Νερά - Γέρακας)', slug: 'fouresi-glyka-nera-gerakas', prefecture: 'Αττικής' },
  { name: 'Φραγκοκκλησιά (Χαλάνδρι Αττικής)', slug: 'fragkokklisia-chalandri-attikis', prefecture: 'Αττικής' },
  { name: 'Φυλή Αττικής', slug: 'fyli-attikis', prefecture: 'Αττικής' },
  { name: 'Χαϊδάρι', slug: 'chaidari-attikis', prefecture: 'Αττικής' },
  { name: 'Χαλάνδρι', slug: 'chalandri-attikis', prefecture: 'Αττικής' },
  { name: 'Χαραυγή - Πύργος Δουκίσσης Πλακεντίας (Πεντέλη Αττικής)', slug: 'charavgi-pyrgos-doukissis-plakentias-penteli-attikis', prefecture: 'Αττικής' },
  { name: 'Χαροκόπου (Καλλιθέα Αττικής)', slug: 'charokopou-kallithea-attikis', prefecture: 'Αττικής' },
  { name: 'Χίλτον (Αθήνα)', slug: 'chilton-athina', prefecture: 'Αττικής' },
  { name: 'Χολαργός', slug: 'cholargos-attikis', prefecture: 'Αττικής' },
  { name: 'Χρυσάκη (Καλλιθέα - Νέα Σμύρνη)', slug: 'chrysaki-kallithea-nea-smyrni', prefecture: 'Αττικής' },
  { name: 'Χρυσούπολη (Περιστέρι Αττικής)', slug: 'chrysoupoli-peristeri-attikis', prefecture: 'Αττικής' },
  { name: 'Χωράφα (Περιστέρι Αττικής)', slug: 'chorafa-peristeri-attikis', prefecture: 'Αττικής' },
  { name: 'Ψαλίδι (Μαρούσι - Ηράκλειο)', slug: 'psalidi-marousi-irakleio', prefecture: 'Αττικής' },
  { name: 'Ψυρρή (Αθήνα)', slug: 'psyrri-athina', prefecture: 'Αττικής' },
  { name: 'Ψυχικό', slug: 'psychiko-attikis', prefecture: 'Αττικής' },
  { name: 'Ωρωπός', slug: 'oropos-attikis', prefecture: 'Αττικής' },
];
