import { CityConfig } from '../types';

// Θεσσαλονίκης (148 cities) - extracted from xo.gr
export const THESSALONIKIS_CITIES: CityConfig[] = [
  { name: 'Αγγελοχώρι Θεσσαλονίκης', slug: 'angelochori-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Αγία Σοφία (Θεσσαλονίκη)', slug: 'agia-sofia-thessaloniki', prefecture: 'Θεσσαλονίκης' },
  { name: 'Αγία Τριάδα (Θεσσαλονίκη)', slug: 'agia-triada-thessaloniki', prefecture: 'Θεσσαλονίκης' },
  { name: 'Αγία Τριάδα Θεσσαλονίκης', slug: 'agia-triada-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Άγιοι Κύριλλος και Μεθόδιος (Εύοσμος Θεσσαλονίκης)', slug: 'agioi-kyrillos-kai-methodios-eyosmos-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Άγιοι Πάντες - Στροφή Επταλόφου (Θεσσαλονίκη)', slug: 'agioi-pantes-strofi-eptalofou-thessaloniki', prefecture: 'Θεσσαλονίκης' },
  { name: 'Άγιος Αθανάσιος (Εύοσμος Θεσσαλονίκης)', slug: 'agios-athanasios-eyosmos-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Άγιος Αθανάσιος Θεσσαλονίκης', slug: 'agios-athanasios-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Άγιος Κοσμάς (Εύοσμος Θεσσαλονίκης)', slug: 'agios-kosmas-eyosmos-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Άγιος Νικόλαος Ορφανός (Θεσσαλονίκη)', slug: 'agios-nikolaos-orfanos-thessaloniki', prefecture: 'Θεσσαλονίκης' },
  { name: 'Άγιος Παντελεήμονας (Πολίχνη Θεσσαλονίκης)', slug: 'agios-panteleimonas-polichni-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Αμπελόκηποι Θεσσαλονίκης', slug: 'ampelokipoi-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Αμπελώνες (Σταυρούπολη Θεσσαλονίκης)', slug: 'ampelones-stavroupoli-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Αναγέννηση (Νεάπολη Θεσσαλονίκης)', slug: 'anagennisi-neapoli-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Ανάληψη (Θεσσαλονίκη)', slug: 'analipsi-thessaloniki', prefecture: 'Θεσσαλονίκης' },
  { name: 'Ανατολική Θεσσαλονίκη', slug: 'anatoliki-thessaloniki', prefecture: 'Θεσσαλονίκης' },
  { name: 'Ανατολικό Θεσσαλονίκης', slug: 'anatoliko-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Άνω Εύοσμος (Εύοσμος Θεσσαλονίκης)', slug: 'ano-eyosmos-eyosmos-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Άνω Ηλιούπολη (Σταυρούπολη Θεσσαλονίκης)', slug: 'ano-ilioupoli-stavroupoli-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Άνω Πανόραμα (Πανόραμα Θεσσαλονίκης)', slug: 'ano-panorama-panorama-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Άνω Τούμπα (Θεσσαλονίκη)', slug: 'ano-toumpa-thessaloniki', prefecture: 'Θεσσαλονίκης' },
  { name: 'Άνω Τριανδρια (Τριανδρία Θεσσαλονίκης)', slug: 'ano-triandria-triandria-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Αξιού (Νεάπολη - Θεσσαλονίκη - Αμπελόκηποι)', slug: 'axiou-neapoli-thessaloniki-ampelokipoi', prefecture: 'Θεσσαλονίκης' },
  { name: 'Αρετσού (Καλαμαριά Θεσσαλονίκης)', slug: 'aretsou-kalamaria-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Ασβεστοχώρι Θεσσαλονίκης', slug: 'asvestochori-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Ασπροβάλτα Θεσσαλονίκης', slug: 'asprovalta-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Άσσηρος Θεσσαλονίκης', slug: 'assiros-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Αφροδισίων (Θεσσαλονίκη)', slug: 'afrodision-thessaloniki', prefecture: 'Θεσσαλονίκης' },
  { name: 'Βαθύλακκος Θεσσαλονίκης', slug: 'vathylakkos-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Βαλσαμή (Νεάπολη Θεσσαλονίκης)', slug: 'valsami-neapoli-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Βότση (Καλαμαριά Θεσσαλονίκης)', slug: 'votsi-kalamaria-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Βούλγαρη (Θεσσαλονίκη)', slug: 'voulgari-thessaloniki', prefecture: 'Θεσσαλονίκης' },
  { name: 'Βρυσάκι (Θεσσαλονίκη)', slug: 'vrysaki-thessaloniki', prefecture: 'Θεσσαλονίκης' },
  { name: 'Βυζάντιο (Καλαμαριά Θεσσαλονίκης)', slug: 'vyzantio-kalamaria-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Γαλαξίας (Θεσσαλονίκη)', slug: 'galaxias-thessaloniki', prefecture: 'Θεσσαλονίκης' },
  { name: 'Γέφυρα Θεσσαλονίκης', slug: 'gefyra-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Δέρκων (Καλαμαριά Θεσσαλονίκης)', slug: 'derkon-kalamaria-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Διοικητήριο (Θεσσαλονίκη)', slug: 'dioikitirio-thessaloniki', prefecture: 'Θεσσαλονίκης' },
  { name: 'Δρυμός Θεσσαλονίκης', slug: 'drymos-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Δυτική Θεσσαλονίκη', slug: 'dytiki-thessaloniki', prefecture: 'Θεσσαλονίκης' },
  { name: 'Ελαιόρεμα (Πυλαία Θεσσαλονίκης)', slug: 'elaiorema-pylaia-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Ελευθέριο - Κορδελιό Θεσσαλονίκης', slug: 'eleftherio-kordelio-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Εξοχή Θεσσαλονίκης', slug: 'exochi-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Επανομή Θεσσαλονίκης', slug: 'epanomi-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Επτάλοφος - Φιλίππου (Αμπελόκηποι Θεσσαλονίκης)', slug: 'eptalofos-filippou-ampelokipoi-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Επταπύργιο (Θεσσαλονίκη - Συκιές)', slug: 'eptapyrgio-thessaloniki-sykies', prefecture: 'Θεσσαλονίκης' },
  { name: 'Εργατικές Κατοικίες Φοίνικα (Καλαμαριά Θεσσαλονίκης)', slug: 'ergatikes-katoikies-foinika-kalamaria-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Ευαγγελισμός - Νέος Κουκλουτζάς (Εύοσμος Θεσσαλονίκης)', slug: 'evangelismos-neos-koukloutzas-eyosmos-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Ευζώνων - Γαλλικό Ινστιτούτο (Θεσσαλονίκη)', slug: 'evzonon-galliko-institouto-thessaloniki', prefecture: 'Θεσσαλονίκης' },
  { name: 'Ευκαρπία Θεσσαλονίκης', slug: 'efkarpia-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Ευκλείδη (Θεσσαλονίκη)', slug: 'efkleidi-thessaloniki', prefecture: 'Θεσσαλονίκης' },
  { name: 'Εύοσμος', slug: 'eyosmos-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Ζαγκλιβέρι Θεσσαλονίκης', slug: 'zagkliveri-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Ηράκλειο Θεσσαλονίκης', slug: 'irakleio-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Θέρμη Θεσσαλονίκης', slug: 'thermi-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Θεσσαλονίκη (Κέντρο - Δήμος)', slug: 'thessaloniki', prefecture: 'Θεσσαλονίκης' },
  { name: 'Ιπποκράτειο (Θεσσαλονίκη)', slug: 'ippokrateio-thessaloniki', prefecture: 'Θεσσαλονίκης' },
  { name: 'Καβαλλάρι Θεσσαλονίκης', slug: 'kavallari-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Καΐστρι (Αμπελόκηποι Θεσσαλονίκης)', slug: 'kaistri-ampelokipoi-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Καλαμαριά', slug: 'kalamaria-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Καλλιθέα (Συκιές - Νεάπολη)', slug: 'kallithea-sykies-neapoli', prefecture: 'Θεσσαλονίκης' },
  { name: 'Καλοχώρι Θεσσαλονίκης', slug: 'kalochori-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Καραμπουρνάκι (Καλαμαριά Θεσσαλονίκης)', slug: 'karampournaki-kalamaria-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Καρδία Θεσσαλονίκης', slug: 'kardia-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Καστανάς Θεσσαλονίκης', slug: 'kastanas-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Κατιρλί (Καλαμαριά Θεσσαλονίκης)', slug: 'katirli-kalamaria-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Κάτω Εύοσμος (Εύοσμος Θεσσαλονίκης)', slug: 'kato-eyosmos-eyosmos-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Κάτω Ηλιούπολη (Εύοσμος - Σταυρούπολη)', slug: 'kato-ilioupoli-eyosmos-stavroupoli', prefecture: 'Θεσσαλονίκης' },
  { name: 'Κάτω Σχολάρι Θεσσαλονίκης', slug: 'kato-scholari-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Κάτω Τούμπα (Θεσσαλονίκη)', slug: 'kato-toumpa-thessaloniki', prefecture: 'Θεσσαλονίκης' },
  { name: 'Κεντρική Θεσσαλονίκη', slug: 'kentriki-thessaloniki', prefecture: 'Θεσσαλονίκης' },
  { name: 'Κέντρο (Καλαμαριά Θεσσαλονίκης)', slug: 'kentro-kalamaria-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Κηφισιά (Καλαμαριά - Θεσσαλονίκη)', slug: 'kifisia-kalamaria-thessaloniki', prefecture: 'Θεσσαλονίκης' },
  { name: 'Κινέζικη Αγορά (Θεσσαλονίκη)', slug: 'kineziki-agora-thessaloniki', prefecture: 'Θεσσαλονίκης' },
  { name: 'Κόκκορας (Νεάπολη - Πολίχνη)', slug: 'kokkoras-neapoli-polichni', prefecture: 'Θεσσαλονίκης' },
  { name: 'Κολοκοτρώνη (Νεάπολη Θεσσαλονίκης)', slug: 'kolokotroni-neapoli-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Κολόμβου - Παλιό Δημαρχείο (Θεσσαλονίκη)', slug: 'kolomvou-palio-dimarcheio-thessaloniki', prefecture: 'Θεσσαλονίκης' },
  { name: 'Κολχικό Θεσσαλονίκης', slug: 'kolchiko-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Κουλέ Καφέ (Θεσσαλονίκη)', slug: 'koule-kafe-thessaloniki', prefecture: 'Θεσσαλονίκης' },
  { name: 'Κουρί (Καλαμαριά Θεσσαλονίκης)', slug: 'kouri-kalamaria-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Κουφάλια Θεσσαλονίκης', slug: 'koufalia-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Κρήτης (Θεσσαλονίκη)', slug: 'kritis-thessaloniki', prefecture: 'Θεσσαλονίκης' },
  { name: 'Κυβέλεια (Θεσσαλονίκη)', slug: 'kyveleia-thessaloniki', prefecture: 'Θεσσαλονίκης' },
  { name: 'Κύμινα Θεσσαλονίκης', slug: 'kymina-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Κωνσταντινουπολίτικα (Πυλαία Θεσσαλονίκης)', slug: 'konstantinoupolitika-pylaia-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Λαγκαδάς Θεσσαλονίκης', slug: 'lagkadas-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Λαγυνά Θεσσαλονίκης', slug: 'lagyna-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Λευκός Πύργος - Ιππόδρομος (Θεσσαλονίκη)', slug: 'lefkos-pyrgos-ippodromos-thessaloniki', prefecture: 'Θεσσαλονίκης' },
  { name: 'Λητή Θεσσαλονίκης', slug: 'liti-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Μαλακοπή (Θεσσαλονίκη - Πυλαία)', slug: 'malakopi-thessaloniki-pylaia', prefecture: 'Θεσσαλονίκης' },
  { name: 'Μελισσοχώρι Θεσσαλονίκης', slug: 'melissochori-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Μενεμένη Θεσσαλονίκης', slug: 'menemeni-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Μεταγωγών (Αμπελόκηποι Θεσσαλονίκης)', slug: 'metagogon-ampelokipoi-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Μετέωρα (Πολίχνη Θεσσαλονίκης)', slug: 'meteora-polichni-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Νέα Απολλωνία Θεσσαλονίκης', slug: 'nea-apollonia-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Νέα Βάρνα (Νεάπολη Θεσσαλονίκης)', slug: 'nea-varna-neapoli-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Νέα Κρήνη (Καλαμαριά Θεσσαλονίκης)', slug: 'nea-krini-kalamaria-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Νέα Μαγνησία Θεσσαλονίκης', slug: 'nea-magnisia-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Νέα Μάδυτος Θεσσαλονίκης', slug: 'nea-madytos-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Νέα Μεσημβρία Θεσσαλονίκης', slug: 'nea-mesimvria-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Νέα Μηχανιώνα Θεσσαλονίκης', slug: 'nea-michaniona-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Νέα Ραιδεστός Θεσσαλονίκης', slug: 'nea-raidestos-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Νεάπολη Θεσσαλονίκης', slug: 'neapoli-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Νέο Ρύσιο Θεσσαλονίκης', slug: 'neo-rysio-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Νέοι Επιβάτες Θεσσαλονίκης', slug: 'neoi-epivates-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Νέος Σιδηροδρομικός Σταθμός - Ζωγράφου (Θεσσαλονίκη)', slug: 'neos-sidirodromikos-stathmos-zografou-thessaloniki', prefecture: 'Θεσσαλονίκης' },
  { name: 'Νεοχωρούδα Θεσσαλονίκης', slug: 'neochorouda-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Νικόπολη (Σταυρούπολη - Πολίχνη - Ευκαρπία)', slug: 'nikopoli-stavroupoli-polichni-efkarpia', prefecture: 'Θεσσαλονίκης' },
  { name: 'Ντεπώ (Θεσσαλονίκη - Καλαμαριά)', slug: 'ntepo-thessaloniki-kalamaria', prefecture: 'Θεσσαλονίκης' },
  { name: 'Ξηροκρήνη (Θεσσαλονίκη - Αμπελόκηποι)', slug: 'xirokrini-thessaloniki-ampelokipoi', prefecture: 'Θεσσαλονίκης' },
  { name: 'Παλιά Σαλαμίνα (Θεσσαλονίκη)', slug: 'palia-salamina-thessaloniki', prefecture: 'Θεσσαλονίκης' },
  { name: 'Πανόραμα Θεσσαλονίκης', slug: 'panorama-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Παράσχου (Συκιές - Νεάπολη)', slug: 'paraschou-sykies-neapoli', prefecture: 'Θεσσαλονίκης' },
  { name: 'Πεντάλοφος Θεσσαλονίκης', slug: 'pentalofos-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Περαία Θεσσαλονίκης', slug: 'peraia-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Πεύκα Θεσσαλονίκης', slug: 'peyka-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Πλαγιάρι Θεσσαλονίκης', slug: 'plagiari-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Πλατεία Καούδη (Θεσσαλονίκη)', slug: 'plateia-kaoudi-thessaloniki', prefecture: 'Θεσσαλονίκης' },
  { name: 'Πλατεία Μηνά Πατρικίου (Θεσσαλονίκη)', slug: 'plateia-mina-patrikiou-thessaloniki', prefecture: 'Θεσσαλονίκης' },
  { name: 'Πολίχνη Θεσσαλονίκης', slug: 'polichni-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Ποσειδώνιο (Θεσσαλονίκη)', slug: 'poseidonio-thessaloniki', prefecture: 'Θεσσαλονίκης' },
  { name: 'Πρόνοια (Σταυρούπολη Θεσσαλονίκης)', slug: 'pronoia-stavroupoli-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Προφήτης Ηλίας (Θεσσαλονίκη)', slug: 'profitis-ilias-thessaloniki', prefecture: 'Θεσσαλονίκης' },
  { name: 'Πυλαία Θεσσαλονίκης', slug: 'pylaia-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Πυροπαθών (Νεάπολη Θεσσαλονίκης)', slug: 'pyropathon-neapoli-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Ρέμα - Καμάρα (Πυλαία Θεσσαλονίκης)', slug: 'rema-kamara-pylaia-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Ροδοχώρι - Αρμενοχώρι (Συκιές Θεσσαλονίκης)', slug: 'rodochori-armenochori-sykies-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Σαμαράκια (Πυλαία Θεσσαλονίκης)', slug: 'samarakia-pylaia-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Σίνδος Θεσσαλονίκης', slug: 'sindos-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Σκεπάρνη (Αμπελόκηποι Θεσσαλονίκης)', slug: 'skeparni-ampelokipoi-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Σουρωτή Θεσσαλονίκης', slug: 'souroti-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Σταγειρίτη (Πυλαία Θεσσαλονίκης)', slug: 'stageiriti-pylaia-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Σταυρός Θεσσαλονίκης', slug: 'stavros-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Σταυρούπολη Θεσσαλονίκης', slug: 'stavroupoli-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Συκιές Θεσσαλονίκης', slug: 'sykies-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Ταγαράδες Θεσσαλονίκης', slug: 'tagarades-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Τερψιθέα (Σταυρούπολη Θεσσαλονίκης)', slug: 'terpsithea-stavroupoli-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Τριανδρία Θεσσαλονίκης', slug: 'triandria-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Τρίλοφο Θεσσαλονίκης', slug: 'trilofo-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Τρωάδα - Άγιος Γεώργιος (Νεάπολη Θεσσαλονίκης)', slug: 'troada-agios-georgios-neapoli-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Τυρολόη (Θεσσαλονίκη)', slug: 'tyroloi-thessaloniki', prefecture: 'Θεσσαλονίκης' },
  { name: 'Φάληρο (Θεσσαλονίκη)', slug: 'faliro-thessaloniki', prefecture: 'Θεσσαλονίκης' },
  { name: 'Φραγκομαχαλάς (Θεσσαλονίκη)', slug: 'fragkomachalas-thessaloniki', prefecture: 'Θεσσαλονίκης' },
  { name: 'Χαλάστρα Θεσσαλονίκης', slug: 'chalastra-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Χαλκηδόνα Θεσσαλονίκης', slug: 'chalkidona-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Χαριλάου (Θεσσαλονίκη)', slug: 'charilaou-thessaloniki', prefecture: 'Θεσσαλονίκης' },
  { name: 'Χορτιάτης Θεσσαλονίκης', slug: 'chortiatis-thessalonikis', prefecture: 'Θεσσαλονίκης' },
  { name: 'Ωραιόκαστρο Θεσσαλονίκης', slug: 'oraiokastro-thessalonikis', prefecture: 'Θεσσαλονίκης' },
];
